### PR TITLE
add uzair@civo.com as owner of the project

### PR DESCRIPTION
**Pull request by alessandroargentieri**
### Description of your changes

Add uzair@civo.com as maintainer of the civo crossplane provider

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

No changes on the codebase have been made

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by RealHarshThakur** [comment]
can we add Vish too?

**Comment by jbw976** [comment]
@alessandroargentieri @RealHarshThakur - I'm following up on making sure these new maintainers are part of the org and have permissions - can you share their Github accounts so I make sure I have the right folks? 🙏

**Comment by uzaxirr** [comment]
> @alessandroargentieri @RealHarshThakur - I'm following up on making sure these new maintainers are part of the org and have permissions - can you share their Github accounts so I make sure I have the right folks? 🙏

Hey @jbw976 
Please find the github accounts listed below
- https://github.com/vishalanarase
- https://github.com/uzaxirr/

**Comment by alessandroargentieri** [comment]
Hi @jbw976  thanks for helping. They are:
- github.com/vishalanarase
- github.com/uzaxirr

**Comment by vishalanarase** [comment]
Thank you @jbw976 🙌 
I have received the invite 👍

**Pull request merged**
