### PR TITLE
Add CNI field to spec

### PR DESCRIPTION
**Pull request by RealHarshThakur**
Signed-off-by: Harsh Thakur <harsh@civo.com>

### Description of your changes

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by RealHarshThakur** [comment]
I wasn't able to find the make recipes to run reviewable, test, or generate deep copy files, crds.

**Comment by haardikdharma10** [comment]
LGTM 👍

**Review by hasheddan — COMMENTED** [review]
@RealHarshThakur it looks like that some of the deepcopy files have not been regenerated, you should be able to update them with `make generate` locally -- let me know if that doesn't produce a diff for you

**Comment by RealHarshThakur** [comment]
It doesn't produce a diff locally and check-diff doesn't complain either
Screenshot 2022-01-20 at 10 11 33 PM

**Comment by alejandrojnm** [comment]
Look good, but the check-diff failed, any idea ??

**Comment by andyjeffries** [comment]
Upstream fails with the same thing according to @RealHarshThakur , so merging.

**Pull request merged**
